version: '3.7'

services:
  proxy:
    build:
      context: ./proxy
    image: symboxtra/splitsound-haproxy
    volumes:
      - ./proxy:/etc/ssl/private
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - splitsound-net

  sig1:
    build:
      context: .
    image: symboxtra/splitsound-signaling-server
    networks:
      - splitsound-net

networks:
  splitsound-net:
    external: false
    driver: bridge